server:
  port: 8080
eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-read-timeout-seconds: 8
    eureka-server-connect-timeout-seconds: 8
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false

