server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: cloud-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
    maxActive: 20
    maxIdle: 20
    maxWait: 9000
    pass: ''
    port: 6379
    testOnBorrow: true

